
/* author : limingfan
 * date : 2017.09.11
 * description : DB代理服务协议码ID定义
 */
 
#ifndef __DBPROXY_PROTOCOL_ID_H__
#define __DBPROXY_PROTOCOL_ID_H__


// DB代理服务协议ID
enum EDBProxyProtocolId
{
	// 设置服务数据
	DBPROXY_SET_SERVICE_DATA_REQ = 1,
	DBPROXY_SET_SERVICE_DATA_RSP = 2,
	
	// 获取服务数据
	DBPROXY_GET_SERVICE_DATA_REQ = 3,
	DBPROXY_GET_SERVICE_DATA_RSP = 4,
	
	// 获取多服务数据
	DBPROXY_GET_MORE_SERVICE_DATA_REQ = 5,
	DBPROXY_GET_MOER_SERVICE_DATA_RSP = 6,
	
	// 删除服务数据
	DBPROXY_DEL_SERVICE_DATA_REQ = 7,
	DBPROXY_DEL_SERVICE_DATA_RSP = 8,
	
	// 获取账号ID
	DBPROXY_GET_USERNAME_REQ = 9,
	DBPROXY_GET_USERNAME_RSP = 10,
	
	// 验证用户，成功则返回用户信息
	DBPROXY_CHECK_USER_REQ = 11,
	DBPROXY_CHECK_USER_RSP = 12,
	
	// 用户登录&登出游戏通知
	DBPROXY_USER_LOGIN_NOTIFY = 13,
	DBPROXY_USER_LOGOUT_NOTIFY = 14,
	
	// 用户充值
	DBPROXY_USER_RECHARGE_REQ = 15,
	DBPROXY_USER_RECHARGE_RSP = 16,
	
	// 获取棋牌室信息
	DBPROXY_GET_CHESS_HALL_INFO_REQ = 17,
	DBPROXY_GET_CHESS_HALL_INFO_RSP = 18,
	
	// 获取棋牌室游戏房间列表
	DBPROXY_GET_HALL_ROOM_LIST_REQ = 19,
	DBPROXY_GET_HALL_ROOM_LIST_RSP = 20,
	
	// 获取棋牌室用户状态信息
	DBPROXY_GET_HALL_PLAYER_STATUS_REQ = 21,
	DBPROXY_GET_HALL_PLAYER_STATUS_RSP = 22,
	
	// 获取棋牌室游戏房间信息
	DBPROXY_GET_GAME_ROOM_INFO_REQ = 23,
	DBPROXY_GET_GAME_ROOM_INFO_RSP = 24,
	
	// 获取用户数据
	DBPROXY_GET_USER_DATA_REQ = 25,
	DBPROXY_GET_USER_DATA_RSP = 26,
	
	// 修改单用户物品数量
	DBPROXY_CHANGE_ITEM_REQ = 27,
	DBPROXY_CHANGE_ITEM_RSP = 28,
	
	// 修改多用户物品数量
	DBPROXY_CHANGE_MORE_USERS_ITEM_REQ = 29,
	DBPROXY_CHANGE_MORE_USERS_ITEM_RSP = 30,
	
	// 玩家进入棋牌室
	DBPROXY_ENTER_CHESS_HALL_REQ = 31,
	DBPROXY_ENTER_CHESS_HALL_RSP = 32,
	
	// 申请加入棋牌室
	DBPROXY_APPLY_JOIN_CHESS_HALL_REQ = 33,
	DBPROXY_APPLY_JOIN_CHESS_HALL_RSP = 34,
	
	// 取消申请加入棋牌室
	DBPROXY_CANCEL_APPLY_CHESS_HALL_REQ = 35,
	DBPROXY_CANCEL_APPLY_CHESS_HALL_RSP = 36,
	
	// 棋牌室管理操作玩家信息
	DBPROXY_MANAGER_OPT_PLAYER_INFO_REQ = 37,
	DBPROXY_MANAGER_OPT_PLAYER_INFO_RSP = 38,
	
	// 创建棋牌室游戏房间
	DBPROXY_CREATE_HALL_GAME_ROOM_REQ = 39,
	DBPROXY_CREATE_HALL_GAME_ROOM_RSP = 40,

	// 修改棋牌室游戏房间状态
	DBPROXY_CHANGE_GAME_ROOM_STATUS_REQ = 41,
	DBPROXY_CHANGE_GAME_ROOM_STATUS_RSP = 42,
	
	// 修改棋牌室游戏房间玩家座位号
	DBPROXY_CHANGE_GAME_ROOM_PLAYER_SEAT_REQ = 43,
	DBPROXY_CHANGE_GAME_ROOM_PLAYER_SEAT_RSP = 44,
	
	// 玩家购买商城物品
	DBPROXY_PLAYER_BUY_MALL_GOODS_REQ = 45,
	DBPROXY_PLAYER_BUY_MALL_GOODS_RSP = 46,
	
	// 玩家获取商城购买记录
	DBPROXY_PLAYER_GET_MALL_BUY_RECORD_REQ = 47,
	DBPROXY_PLAYER_GET_MALL_BUY_RECORD_RSP = 48,
	
	// 管理员赠送物品，玩家确认收货通知
	DBPROXY_PLAYER_CONFIRM_GIVE_GOODS_NOTIFY = 49,
	
	// 服务状态通知
	DBPROXY_SERVICE_STATUS_NOTIFY = 50,
	
	// 获取棋牌室基本信息
	DBPROXY_GET_HALL_BASE_INFO_REQ = 51,
	DBPROXY_GET_HALL_BASE_INFO_RSP = 52,
	
	// 修改用户数据
	DBPROXY_MODIFY_USER_DATA_REQ = 53,
	DBPROXY_MODIFY_USER_DATA_RSP = 54,
	
	// 获取邀请玩家列表
	DBPROXY_GET_INVITATION_LIST_REQ = 55,
	DBPROXY_GET_INVITATION_LIST_RSP = 56,
	
	// 添加最近的游戏玩家
	DBPROXY_ADD_LAST_PLAYERS_REQ = 57,
	DBPROXY_ADD_LAST_PLAYERS_RSP = 58,
	
	// 获取最近的游戏玩家列表
	DBPROXY_GET_LAST_PLAYER_LIST_REQ = 59,
	DBPROXY_GET_LAST_PLAYER_LIST_RSP = 60,
	
	// 棋牌室管理员确认商城购买信息
	DBPROXY_CONFIRM_MALL_BUY_INFO_REQ = 61,
	DBPROXY_CONFIRM_MALL_BUY_INFO_RSP = 62,
	
	// 棋牌室管理员赠送商城礼物
	DBPROXY_GIVE_MALL_GOODS_REQ = 63,
	DBPROXY_GIVE_MALL_GOODS_RSP = 64,
    
    // 获取游戏战绩信息
	DBPROXY_GET_GAME_RECORD_INFO_REQ = 65,
	DBPROXY_GET_GAME_RECORD_INFO_RSP = 66,
	
    // 获取详细游戏战绩信息
	DBPROXY_GET_DETAILED_GAME_RECORD_REQ = 67,
	DBPROXY_GET_DETAILED_GAME_RECORD_RSP = 68,
    
    // 获取棋牌室当前排名列表
	DBPROXY_GET_HALL_RANKING_REQ = 69,
	DBPROXY_GET_HALL_RANKING_RSP = 70,
    
    // 获取用户属性数据值
	DBPROXY_GET_USER_ATTRIBUTE_VALUE_REQ = 71,
	DBPROXY_GET_USER_ATTRIBUTE_VALUE_RSP = 72,
	
	// 创建棋牌室充值信息
	DBPROXY_CREATE_HALL_RECHARGE_INFO_REQ = 73,
	DBPROXY_CREATE_HALL_RECHARGE_INFO_RSP = 74,
	
	// 棋牌室管理员充值
	DBPROXY_MANAGER_RECHARGE_REQ = 75,
	DBPROXY_MANAGER_RECHARGE_RSP = 76,
	
	// 获取棋牌室玩家信息列表
	DBPROXY_GET_HALL_PLAYER_LIST_REQ = 77,
	DBPROXY_GET_HALL_PLAYER_LIST_RSP = 78,
	
	// 设置房间游戏记录
	DBPROXY_SET_ROOM_GAME_RECORD_REQ = 79,
	DBPROXY_SET_ROOM_GAME_RECORD_RSP = 80,
	
	// 查询游戏房间
	DBPROXY_QUERY_GAME_ROOM_REQ = 81,
	DBPROXY_QUERY_GAME_ROOM_RSP = 82,
	
	// 获取房间游戏战绩信息
	DBPROXY_GET_ROOM_GAME_RECORD_REQ = 83,
	DBPROXY_GET_ROOM_GAME_RECORD_RSP = 84,
	
    // 获取详细房间游戏战绩信息
	DBPROXY_GET_DETAILED_ROOM_GAME_RECORD_REQ = 85,
	DBPROXY_GET_DETAILED_ROOM_GAME_RECORD_RSP = 86,
	
	// 房卡购买金币
	DBPROXY_ROOM_CARD_BUY_GOLD_REQ = 87,
	DBPROXY_ROOM_CARD_BUY_GOLD_RSP = 88,
};


#endif // __DBPROXY_PROTOCOL_ID_H__

