
/* author : limingfan
 * date : 2016.11.17
 * description : 各服务协议码ID定义
 */
 
#ifndef __SERVICE_PROTOCOL_ID_H__
#define __SERVICE_PROTOCOL_ID_H__


// 捕鱼类游戏提供的服务协议ID（捕鱼游戏、PK场、比赛场、捕鱼棋牌）
// ServiceType::OutsideClientSrv = 31
enum BuyuTypeClientProtocolId
{
	CLIENT_ENTER_ROOM_VERIFY_REQ = 1,
	CLIENT_ENTER_ROOM_VERIFY_RSP = 2,

	CLIENT_BUYU_ENTER_TABLE_REQ = 3,
	CLIENT_BUYU_ENTER_TABLE_RSP = 4,
	CLIENT_BUYU_ENTER_TABLE_NOTIFY = 5,

	CLIENT_BUYU_SET_BULLET_RATE_REQ = 6,
	CLIENT_BUYU_SET_BULLET_RATE_RSP = 7,
	CLIENT_BUYU_SET_BULLET_RATE_NOTIFY = 8,

	CLIENT_BUYU_SHOOT_BULLET_REQ = 9,
	CLIENT_BUYU_SHOOT_BULLET_RSP = 10,
	CLIENT_BUYU_SHOOT_BULLET_NOTIFY = 11,

	CLIENT_BUYU_HIT_FISH_REQ = 12,
	CLIENT_BUYU_HIT_FISH_RSP = 13,
	CLIENT_BUYU_HIT_FISH_NOTIFY = 14,

	CLIENT_BUYU_QUIT_REQ = 15,
	CLIENT_BUYU_QUIT_RSP = 16,
	CLIENT_BUYU_QUIT_NOTIFY = 17,

	CLIENT_BUYU_CHANGE_SCENE_NOTIFY = 18,
	CLIENT_BUYU_ADD_FISH_TRACE_NOTIFY = 19,

	//	CLIENT_FORCE_QUIT_NOTIFY = 20,

	//好友跟消息
	//S 代表服务，A代表添加好友发起方，B代表被添加好友方
	CLIENT_ADD_FRIEND_REQ = 21,				//A -> S	A给服务发起添加好友B的请求
	CLIENT_ADD_FRIEND_RETRANS_REQ = 22,		//S -> B	服务给B转发A的好友请求
	CLIENT_ADD_FRIEND_RETRANS_RSP = 23,		//B -> S	B应答A的好友请求
	CLIENT_ADD_FRIEND_RSP = 24,				//S -> A	服务给A发送加好友的结果
	//	CLIENT_ADD_FRIEND_NOTIFY = 25,			//S -> B	服务给B发送加好友的结果（若B不同意加好友，不会收到此协议）

	CLIENT_GET_USER_BASEINFO_REQ = 26,
	CLIENT_GET_USER_BASEINFO_RSP = 27,

	CLIENT_REMOVE_FRIEND_REQ = 28,	//ClientRemoveFriendReq
	CLIENT_REMOVE_FRIEND_RSP = 29,	//ClientRemoveFriendRsp

	CLIENT_GET_FRIEND_DYNAMIC_REQ = 30,	//ClientGetFriendDynamicDataReq
	CLIENT_GET_FRIEND_DYNAMIC_RSP = 31, //ClientGetFriendDynamicDataRsp

	CLIENT_PRIVATE_CHAT_REQ = 32,
	CLIENT_PRIVATE_CHAT_RSP = 33,
	CLIENT_PRIVATE_CHAT_NOTIFY = 34,

	CLIENT_TABLE_CHAT_REQ = 35,
	CLIENT_TABLE_CHAT_RSP = 36,
	CLIENT_TABLE_CHAT_NOTIFY = 37,

	CLIENT_WORLD_CHAT_REQ = 38,
	CLIENT_WORLD_CHAT_RSP = 39,
	CLIENT_WORLD_CHAT_NOTIFY = 40,

	//道具
	CLIENT_BUYU_USE_PROP_REQ = 41,
	CLIENT_BUYU_USE_PROP_RSP = 42,
	CLIENT_BUYU_USE_PROP_NOTIFY = 43,

	CLIENT_BUYU_SHOOT_LIGHT_REQ = 44,
	CLIENT_BUYU_SHOOT_LIGHT_RSP = 45,
	CLIENT_BUYU_SHOOT_LIGHT_NOTIFY = 46,

	CLIENT_BUYU_LIGHT_HIT_FISH_REQ = 47,
	CLIENT_BUYU_LIGHT_HIT_FISH_RSP = 48,
	CLIENT_BUYU_LIGHT_HIT_FISH_NOTIFY = 49,

	CLIENT_BUYU_HIT_PROP_REQ = 50,
	CLIENT_BUYU_HIT_PROP_RSP = 51,
	CLIENT_BUYU_HIT_PROP_NOTIFY = 52,

	CLIENT_BUYU_ADD_PROP_TRACE_NOTIFY = 53,

	//更新
	CLIENT_BUYU_VERSION_MANAGE_REQ = 54,
	CLIENT_BUYU_VERSION_MANAGE_RSP = 55,

	//商城
	CLIENT_BUYU_GET_MALL_CONFIG_REQ = 56,
	CLIENT_BUYU_GET_MALL_CONFIG_RSP = 57,

	//用户反溃
	CLIENT_OPINION_INFO_REQ = 58,
	CLIENT_OPINION_INFO_RSP = 59,

	//阅兵结束
	CLIENT_BUYU_PARADE_END_NOTIFY = 60,

	//（新）用户反溃
	CLIENT_GET_HISTORY_OPINION_REQ = 61,
	CLIENT_GET_HISTORY_OPINION_RSP = 62,
	CLIENT_UPLOAD_NEW_OPINION_REQ = 63,
	CLIENT_UPLOAD_NEW_OPINION_RSP = 64,
	CLIENT_CS_REPLY_OPINION_NOTIFY = 65,
	CLIENT_USER_ADD_OPINION_ASK_REQ = 66,
	CLIENT_USER_ADD_OPINION_ASK_RSP = 67,

	//金币过多通知
	CLIENT_USER_GOLD_MORE_ENOUGH_NOTIFY = 68,

	//好友赠金币
	CLIENT_FRIEND_DONATE_GOLD_REQ = 69,
	CLIENT_FRIEND_DONATE_GOLD_RSP = 70,
	CLIENT_FRIEND_DONATE_GOLD_NOTIFY = 71,
	
	// 当乐平台充值
	CLIENT_GET_DOWNJOY_RECHARGE_TRANSACTION_REQ = 72,
	CLIENT_GET_DOWNJOY_RECHARGE_TRANSACTION_RSP = 73,
	CLIENT_DOWNJOY_RECHARGE_TRANSACTION_NOTIFY = 74,
	CLIENT_CANCEL_DOWNJOY_RECHARGE_NOTIFY = 75,

	//兑换
	CLIENT_EXCHANGE_PHONE_CARD_REQ = 76,
	CLIENT_EXCHANGE_PHONE_CARD_RSP = 77,
	CLIENT_EXCHANGE_GOODS_REQ = 78,
	CLIENT_EXCHANGE_GOODS_RSP = 79,

	//属性变更通知
	CLIENT_USER_ATTR_CHANGE_NOTIFY = 80,

	// 破产补助免费赠送金币
	CLIENT_NO_GOLD_FREE_GIVE_REQ = 81,
	CLIENT_NO_GOLD_FREE_GIVE_RSP = 82,
	CLIENT_GET_NO_GOLD_FREE_GIVE_REQ = 83,
	CLIENT_GET_NO_GOLD_FREE_GIVE_RSP = 84,

	//系统消息通知
	CLIENT_SYSTEM_MESSAGE_NOTIFY = 85,

	//用户切换到高倍场
	CLIENT_GOTO_HIGH_TIMES_REQ = 86,
	CLIENT_GOTO_HIGH_TIMES_RSP = 87,

	//代理机器人
	CLIENT_PROXY_OTHER_NOTIFY = 88,
	CLIENT_BUYU_SHOOT_BULLET_PROXY_REQ = 89,
	CLIENT_BUYU_HIT_FISH_PROXY_REQ = 90,
	CLIENT_BUYU_USE_PROP_PROXY_REQ = 91,
	CLIENT_BUYU_SHOOT_LIGHT_PROXY_REQ = 92,
	CLIENT_BUYU_LIGHT_HIT_FISH_PROXY_REQ = 93,

	//用户升级通知
	CLIENT_BUYU_LEVEL_UP_NOTIFY = 94,
	
	// 海外版本广告视频获取奖励
	CLIENT_GET_OVERSEAS_VIDEO_REWARD_REQ = 95,
	CLIENT_GET_OVERSEAS_VIDEO_REWARD_RSP = 96,
	
	// Google SDK 充值操作
	CLIENT_GET_GOOGLE_RECHARGE_REQ = 97,
	CLIENT_GET_GOOGLE_RECHARGE_RSP = 98,
	CLIENT_CHECK_GOOGLE_RECHARGE_REQ = 99,
	CLIENT_CHECK_GOOGLE_RECHARGE_RSP = 100,
	
	// 第三方平台操作
	CLIENT_THIRD_RECHARGE_TRANSACTION_REQ = 101,
	CLIENT_THIRD_RECHARGE_TRANSACTION_RSP = 102,
	CLIENT_THIRD_RECHARGE_TRANSACTION_NOTIFY = 103,
	CLIENT_CANCEL_THIRD_RECHARGE_NOTIFY = 104,

	// 通知前端玩家必须退出游戏
	CLIENT_PLAYER_QUIT_NOTIFY = 105,
	
	// 任务操作
	CLIENT_VIEW_TASK_STATUS_REQ = 106,
	CLIENT_UPDATE_TASK_PROGRESS_NOTIFY = 107,
	CLIENT_TASK_REWARD_NOTIFY = 108,
	CLIENT_RECEIVE_TASK_REWARD_REQ = 109,
	CLIENT_RECEIVE_TASK_REWARD_RSP = 110,
	
	// 道具数量变更通知
	CLIENT_PROP_CHANGE_NOTIFY = 111,
	
	// 获取鱼类的倍率分值
	CLIENT_GET_FISH_RATE_SCORE_REQ = 112,
	CLIENT_GET_FISH_RATE_SCORE_RSP = 113,

	// 查询腾讯充值是否成功
	CLIENT_FIND_RECHARGE_SUCCESS_REQ = 114,
	CLIENT_FIND_RECHARGE_SUCCESS_RSP = 115,

	//炮台升级
	CLIENT_BATTERY_UPDATE_REQ = 116,
	CLIENT_BATTERY_UPDATE_RSP = 117,
	
	
	// 获取游戏商城配置
	CLIENT_GET_GAME_MALL_CONFIG_REQ = 118,
	CLIENT_GET_GAME_MALL_CONFIG_RSP = 119,

	// 兑换游戏商品
	CLIENT_EXCHANGE_GAME_GOODS_REQ = 120,
	CLIENT_EXCHANGE_GAME_GOODS_RSP = 121,
	
	// 充值渔币
	CLIENT_GET_RECHARGE_FISH_COIN_ORDER_REQ = 122,
	CLIENT_GET_RECHARGE_FISH_COIN_ORDER_RSP = 123,
	CLIENT_RECHARGE_FISH_COIN_NOTIFY = 124,
	CLIENT_CANCEL_RECHARGE_FISH_COIN_NOTIFY = 125,
	
	// 获取首冲礼包信息
	CLIENT_GET_FIRST_PACKAGE_INFO_REQ = 126,
	CLIENT_GET_FIRST_PACKAGE_INFO_RSP = 127,

	//炮台可升级通知
	CLIENT_BATTERY_UPDATE_NOTIFY = 128,

	//活动
	CLIENT_ACTIVITY_START_NOTIFY = 129,	//活动开始
	CLIENT_ACTIVITY_END_NOTIFY = 130,	//活动结束
	CLIENT_ACTIVITY_UPDATA_TIME_NOTIFY = 131,	//更新活动时间

	CLIENT_BATTERY_UPDATE_TABLE_NOTIFY = 132,		//通知同桌 玩家炮台升级
	CLIENT_ACTIVITY_RANKING_NOTIFY = 133,			//活动排名
	CLIENT_ACTIVITY_PACE_UPDATE_NOTIFY = 134,		//玩家活动进度更新

	CLIENT_USER_LOGIN_SCENE_SUCCESS_REQ = 135,		//玩家登录场景成功后
	

	// 获取实物兑换信息
	CLIENT_GET_EXCHANGE_CONFIG_REQ = 136,
	CLIENT_GET_EXCHANGE_CONFIG_RSP = 137,
	
	// 兑换话费额度
	CLIENT_EXCHANGE_PHONE_FARE_REQ = 138,
	CLIENT_EXCHANGE_PHONE_FARE_RSP = 139,
	
	// 捕获特殊鱼
	CLIENT_BUYU_HIT_SPECIAL_FISH_REQ = 140,          // 玩家捕获特殊鱼请求
	CLIENT_BUYU_HIT_SPECIAL_FISH_NOTIFY = 141,
	CLIENT_BUYU_HIT_SPECIAL_FISH_PROXY_REQ = 142,    // 机器人捕获特殊鱼请求

	// 获取炮台信息
	CLIENT_BUYU_BATTERY_INFO_REQ = 143,
	CLIENT_BUYU_BATTERY_INFO_RSP = 144,

	//更换炮台皮肤
	CLIENT_BUYU_CHANGE_BATTERY_SKIN_REQ = 145,
	CLIENT_BUYU_CHANGE_BATTERY_SKIN_RSP = 146,
	CLIENT_BUYU_CHANGE_BATTERY_SKIN_NOTIFY = 147,	

	//狂暴状态下发子弹
	CLIENT_BUYU_RAMPAGE_SHOOT_BULLET_REQ = 148,
	CLIENT_BUYU_RAMPAGE_SHOOT_BULLET_RSP = 149,
	CLIENT_BUYU_RAMPAGE_SHOOT_BULLET_NOTIFY = 150,

	CLIENT_BUYU_PK_PLAY_WAGER_NOTIFY = 151,			// PK场加注通知
	CLIENT_BUYU_PK_PLAY_WAGER_REQ = 152,			// PK场加注请求
	CLIENT_BUYU_PK_PLAY_WAGER_RSP = 153,			// PK场加注应答
	CLIENT_BUYU_PK_PLAY_WAGER_RESULT_NOTIFY = 154,  // PK场加注结果通知
	
	CLIENT_BUYU_PK_PLAY_RESULT_NOTIFY = 155,		// PK场结算通知

	CLIENT_BUYU_PK_PLAY_START_NOTIFY = 156,			// PK场游戏开始
	CLIENT_BUYU_PK_PLAY_UPDATE_TIME_NOTIFY = 157,	// PK场游戏时间更新
	CLIENT_BUYU_PK_PLAY_RANKING_NOTIFY = 158,		// PK场排名更新
	CLIENT_BUYU_PK_PLAY_INIT_NOTIFY = 159,			// PK场初始化通知

	CLIENT_BUYU_PK_PLAY_WAGER_TABLE_NOTIFY = 160,	// PK场加注应答 通知同桌人
	
	CLIENT_BUYU_PK_PLAY_OTHER_WAIVER_NOTIFY = 161,	// pk场其他玩家弃权通知
	
	CLIENT_BUYU_SHARE_REQ = 162,					// 分享请求
	CLIENT_BUYU_SHARE_RSP = 163,					// 分享应答
	
	CLIENT_BUYU_READ_SYSTEM_MSG_NOTIFY = 164,	    // 已读系统消息通知

	CLIENT_SERVICE_HEART_BEAT_NOTIFY = 165,	        // 服务应用心跳消息

	//被动引导提示通知(自己金币够时)
	CLIENT_BUYU_PK_PASSIVE_GUIDE_NOTIFY = 166,
	CLIENT_BUYU_PK_PASSIVE_GUIDE_REQ = 167,
	CLIENT_BUYU_PK_PASSIVE_GUIDE_RSP = 168,

	//主动引导提示通知(有人PK 系统推送来的)
	CLIENT_BUYU_PK_ACTIVE_GUIDE_NOTIFY = 169,
	CLIENT_BUYU_PK_ACTIVE_GUIDE_REQ = 170,
	CLIENT_BUYU_PK_ACTIVE_GUIDE_RSP = 171,
	
    // 比赛场通知
	CLIENT_BUYU_ARENA_UPDATE_SCORE_RANKING_NOTIFY = 172,
	CLIENT_BUYU_ARENA_UPDATE_TIME_NOTIFY = 173,
	CLIENT_BUYU_ARENA_FINISH_NOTIFY = 174,
	
	// 捕鱼棋牌相关
	// 进入 捕鱼棋牌
	CLIENT_BUYU_CHESS_ENTER_REQ = 175,
	CLIENT_BUYU_CHESS_ENTER_RSP = 176,
	
	// 报名参赛 捕鱼棋牌
	CLIENT_BUYU_CHESS_SIGN_MATCH_REQ = 177,
	CLIENT_BUYU_CHESS_SIGN_MATCH_RSP = 178,
	CLIENT_BUYU_CHESS_SIGN_MATCH_NOTIFY = 179,
	
	// 捕鱼棋牌 玩家进入场景同步数据通知前端
	CLIENT_BUYU_CHESS_ENTER_SCENE_NOTIFY = 180,
	
	// 玩家选择 击中鱼掉落下来的卡牌
	CLIENT_BUYU_CHESS_CHOICE_POKER_REQ = 181,
	CLIENT_BUYU_CHESS_CHOICE_POKER_RSP = 182,
	CLIENT_BUYU_CHESS_CHOICE_POKER_NOTIFY = 183,
	
	// 捕鱼棋牌 结算通知玩家
	CLIENT_BUYU_CHESS_SETTLEMENT_NOTIFY = 184,
	
	// 苹果版本充值结果验证通知
	CLIENT_APPLE_RECHARGE_RESULT_NOTIFY = 185,
};


// 测试协议ID
enum ETestProtocolId
{
	// 异步消息本地数据存取测试
    ETEST_ASYNC_MSG_LOCAL_DATA_REQ = 8001,
	ETEST_ASYNC_MSG_LOCAL_DATA_RSP = 8002,
};


#endif // __SERVICE_PROTOCOL_ID_H__

